package com.mantelgroup.appfunctionsdemo.ui

enum class GroceryCategory(val displayName: String) {
    PRODUCE("Produce"),
    DAIRY("Dairy & Chilled"),
    MEAT_AND_SEAFOOD("Meat & Seafood"),
    BAKERY("Bakery"),
    PANTRY("Pantry"),
    BEVERAGES("Beverages"),
}

enum class GroceryItem(
    val displayName: String,
    val price: Double,
    val emoji: String,
    val category: GroceryCategory,
) {
    APPLES("Apples", 1.99, "\uD83C\uDF4E", GroceryCategory.PRODUCE),
    GREEN_APPLES("Green Apples", 1.99, "\uD83C\uDF4F", GroceryCategory.PRODUCE),
    PEARS("Pears", 1.79, "\uD83C\uDF50", GroceryCategory.PRODUCE),
    BANANAS("Bananas", 0.99, "\uD83C\uDF4C", GroceryCategory.PRODUCE),
    ORANGES("Oranges", 1.49, "\uD83C\uDF4A", GroceryCategory.PRODUCE),
    LEMONS("Lemons", 1.29, "\uD83C\uDF4B", GroceryCategory.PRODUCE),
    STRAWBERRIES("Strawberries", 3.49, "\uD83C\uDF53", GroceryCategory.PRODUCE),
    BLUEBERRIES("Blueberries", 4.99, "\uD83E\uDED0", GroceryCategory.PRODUCE),
    GRAPES("Grapes", 2.99, "\uD83C\uDF47", GroceryCategory.PRODUCE),
    CHERRIES("Cherries", 3.99, "\uD83C\uDF52", GroceryCategory.PRODUCE),
    WATERMELON("Watermelon", 5.99, "\uD83C\uDF49", GroceryCategory.PRODUCE),
    PINEAPPLE("Pineapple", 3.99, "\uD83C\uDF4D", GroceryCategory.PRODUCE),
    MANGO("Mango", 1.79, "\uD83E\uDD6D", GroceryCategory.PRODUCE),
    KIWI("Kiwi", 1.29, "\uD83E\uDD5D", GroceryCategory.PRODUCE),
    PEACHES("Peaches", 2.49, "\uD83C\uDF51", GroceryCategory.PRODUCE),
    AVOCADOS("Avocados", 1.49, "\uD83E\uDD51", GroceryCategory.PRODUCE),
    TOMATOES("Tomatoes", 1.99, "\uD83C\uDF45", GroceryCategory.PRODUCE),
    BROCCOLI("Broccoli", 1.99, "\uD83E\uDD66", GroceryCategory.PRODUCE),
    SPINACH("Spinach", 2.49, "\uD83E\uDD6C", GroceryCategory.PRODUCE),
    LETTUCE("Lettuce", 1.79, "\uD83E\uDD6C", GroceryCategory.PRODUCE),
    CARROTS("Carrots", 1.29, "\uD83E\uDD55", GroceryCategory.PRODUCE),
    BELL_PEPPERS("Bell Peppers", 1.49, "\uD83E\uDED1", GroceryCategory.PRODUCE),
    CUCUMBER("Cucumber", 1.29, "\uD83E\uDD52", GroceryCategory.PRODUCE),
    EGGPLANT("Eggplant", 1.49, "\uD83C\uDF46", GroceryCategory.PRODUCE),
    CORN("Corn", 0.99, "\uD83C\uDF3D", GroceryCategory.PRODUCE),
    MUSHROOMS("Mushrooms", 2.49, "\uD83C\uDF44", GroceryCategory.PRODUCE),
    ONIONS("Onions", 0.99, "\uD83E\uDDC5", GroceryCategory.PRODUCE),
    GARLIC("Garlic", 0.79, "\uD83E\uDDC4", GroceryCategory.PRODUCE),
    POTATOES("Potatoes", 2.49, "\uD83E\uDD54", GroceryCategory.PRODUCE),
    SWEET_POTATOES("Sweet Potatoes", 1.99, "\uD83C\uDF60", GroceryCategory.PRODUCE),
    PEANUTS("Peanuts", 2.99, "\uD83E\uDD5C", GroceryCategory.PRODUCE),

    MILK("Milk", 2.99, "\uD83E\uDD5B", GroceryCategory.DAIRY),
    BUTTER("Butter", 3.49, "\uD83E\uDDC8", GroceryCategory.DAIRY),
    CHEESE("Cheese", 4.99, "\uD83E\uDDC0", GroceryCategory.DAIRY),
    YOGURT("Yogurt", 1.99, "\uD83E\uDD63", GroceryCategory.DAIRY),
    EGGS("Eggs", 3.99, "\uD83E\uDD5A", GroceryCategory.DAIRY),
    ICE_CREAM("Ice Cream", 4.49, "\uD83C\uDF66", GroceryCategory.DAIRY),

    CHICKEN_BREAST("Chicken Breast", 7.99, "\uD83C\uDF57", GroceryCategory.MEAT_AND_SEAFOOD),
    GROUND_BEEF("Ground Beef", 6.49, "\uD83E\uDD69", GroceryCategory.MEAT_AND_SEAFOOD),
    SALMON("Salmon", 10.99, "\uD83D\uDC1F", GroceryCategory.MEAT_AND_SEAFOOD),
    SHRIMP("Shrimp", 9.99, "\uD83E\uDD90", GroceryCategory.MEAT_AND_SEAFOOD),
    BACON("Bacon", 5.99, "\uD83E\uDD53", GroceryCategory.MEAT_AND_SEAFOOD),
    LOBSTER("Lobster", 14.99, "\uD83E\uDD9E", GroceryCategory.MEAT_AND_SEAFOOD),
    CRAB("Crab", 12.99, "\uD83E\uDD80", GroceryCategory.MEAT_AND_SEAFOOD),

    BREAD("Bread", 2.49, "\uD83C\uDF5E", GroceryCategory.BAKERY),
    BAGUETTE("Baguette", 3.29, "\uD83E\uDD56", GroceryCategory.BAKERY),
    BAGELS("Bagels", 3.29, "\uD83E\uDD6F", GroceryCategory.BAKERY),
    CROISSANTS("Croissants", 4.49, "\uD83E\uDD50", GroceryCategory.BAKERY),
    PRETZEL("Pretzel", 2.79, "\uD83E\uDD68", GroceryCategory.BAKERY),
    WAFFLES("Waffles", 3.99, "\uD83E\uDDC7", GroceryCategory.BAKERY),
    PANCAKES("Pancakes", 3.99, "\uD83E\uDD5E", GroceryCategory.BAKERY),
    TORTILLAS("Tortillas", 2.79, "\uD83E\uDED3", GroceryCategory.BAKERY),

    PASTA("Pasta", 1.79, "\uD83C\uDF5D", GroceryCategory.PANTRY),
    RICE("Rice", 2.99, "\uD83C\uDF5A", GroceryCategory.PANTRY),
    QUINOA("Quinoa", 4.99, "\uD83C\uDF3E", GroceryCategory.PANTRY),
    OATS("Oats", 3.49, "\uD83E\uDD63", GroceryCategory.PANTRY),
    CEREAL("Cereal", 3.99, "\uD83E\uDD63", GroceryCategory.PANTRY),
    CANNED_FOOD("Canned Food", 2.49, "\uD83E\uDD6B", GroceryCategory.PANTRY),
    OLIVE_OIL("Olive Oil", 16.99, "\uD83E\uDED7", GroceryCategory.PANTRY),
    OLIVES("Olives", 3.49, "\uD83E\uDED2", GroceryCategory.PANTRY),
    SOY_SAUCE("Soy Sauce", 2.49, "\uD83C\uDF76", GroceryCategory.PANTRY),
    HOT_SAUCE("Hot Sauce", 2.99, "\uD83C\uDF36", GroceryCategory.PANTRY),
    KETCHUP("Ketchup", 1.99, "\uD83E\uDED9", GroceryCategory.PANTRY),
    MUSTARD("Mustard", 1.79, "\uD83D\uDFE1", GroceryCategory.PANTRY),
    HONEY("Honey", 5.99, "\uD83C\uDF6F", GroceryCategory.PANTRY),
    SALT("Salt", 1.29, "\uD83E\uDDC2", GroceryCategory.PANTRY),
    POPCORN("Popcorn", 2.99, "\uD83C\uDF7F", GroceryCategory.PANTRY),
    CHOCOLATE("Chocolate", 3.99, "\uD83C\uDF6B", GroceryCategory.PANTRY),
    PEANUT_BUTTER("Peanut Butter", 3.99, "\uD83E\uDD5C", GroceryCategory.PANTRY),

    ORANGE_JUICE("Orange Juice", 3.99, "\uD83E\uDDC3", GroceryCategory.BEVERAGES),
    JUICE("Juice", 3.49, "\uD83E\uDDC3", GroceryCategory.BEVERAGES),
    SODA("Soda", 1.99, "\uD83E\uDD64", GroceryCategory.BEVERAGES),
    COFFEE("Coffee", 8.99, "\u2615", GroceryCategory.BEVERAGES),
    GREEN_TEA("Green Tea", 4.49, "\uD83C\uDF75", GroceryCategory.BEVERAGES),
    SPARKLING_WATER("Sparkling Water", 1.49, "\uD83D\uDCA6", GroceryCategory.BEVERAGES),
    ALMOND_MILK("Almond Milk", 3.99, "\uD83E\uDD5B", GroceryCategory.BEVERAGES),
    BEER("Beer", 7.99, "\uD83C\uDF7A", GroceryCategory.BEVERAGES),
    WINE("Wine", 12.99, "\uD83C\uDF77", GroceryCategory.BEVERAGES),
}
