package com.mantelgroup.appfunctionsdemo.ui

enum class GroceryItem(val displayName: String, val price: Double) {
    APPLES("Apples", 1.99),
    BANANAS("Bananas", 0.99),
    ORANGES("Oranges", 1.49),
    STRAWBERRIES("Strawberries", 3.49),
    BLUEBERRIES("Blueberries", 4.99),
    GRAPES("Grapes", 2.99),
    WATERMELON("Watermelon", 5.99),
    PINEAPPLE("Pineapple", 3.99),
    MANGO("Mango", 1.79),
    PEACHES("Peaches", 2.49),
    MILK("Milk", 2.99),
    BUTTER("Butter", 3.49),
    CHEESE("Cheese", 4.99),
    YOGURT("Yogurt", 1.99),
    EGGS("Eggs", 3.99),
    BREAD("Bread", 2.49),
    BAGELS("Bagels", 3.29),
    CROISSANTS("Croissants", 4.49),
    TORTILLAS("Tortillas", 2.79),
    PITA_BREAD("Pita Bread", 2.99),
    CHICKEN_BREAST("Chicken Breast", 7.99),
    GROUND_BEEF("Ground Beef", 6.49),
    SALMON("Salmon", 10.99),
    SHRIMP("Shrimp", 9.99),
    BACON("Bacon", 5.99),
    BROCCOLI("Broccoli", 1.99),
    SPINACH("Spinach", 2.49),
    CARROTS("Carrots", 1.29),
    BELL_PEPPERS("Bell Peppers", 1.49),
    TOMATOES("Tomatoes", 1.99),
    ONIONS("Onions", 0.99),
    GARLIC("Garlic", 0.79),
    POTATOES("Potatoes", 2.49),
    SWEET_POTATOES("Sweet Potatoes", 1.99),
    AVOCADOS("Avocados", 1.49),
    PASTA("Pasta", 1.79),
    RICE("Rice", 2.99),
    QUINOA("Quinoa", 4.99),
    OATS("Oats", 3.49),
    CEREAL("Cereal", 3.99),
    OLIVE_OIL("Olive Oil", 16.99),
    SOY_SAUCE("Soy Sauce", 2.49),
    HOT_SAUCE("Hot Sauce", 2.99),
    KETCHUP("Ketchup", 1.99),
    MUSTARD("Mustard", 1.79),
    ORANGE_JUICE("Orange Juice", 3.99),
    COFFEE("Coffee", 8.99),
    GREEN_TEA("Green Tea", 4.49),
    SPARKLING_WATER("Sparkling Water", 1.49),
    ALMOND_MILK("Almond Milk", 3.99),
}
